# Generated by Django 5.2.7 on 2025-10-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_service_remove_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('master', 'Master Room'), ('meeting', 'Meeting Room'), ('deluxe', 'Deluxe Room'), ('executive', 'Executive Room'), ('suite', 'Luxury Suite')], default='single', max_length=20),
        ),
    ]
