# Generated by Django 5.2.7 on 2025-10-30 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_review_service_remove_booking_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('cnic', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9\\-]{13,20}$', 'Enter a valid CNIC number.')])),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single Bedroom'), ('master', 'Master Bedroom')], max_length=20)),
                ('booking_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('airport_pick_drop', models.BooleanField(default=False)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_reference'], name='bookings_bo_booking_8a7545_idx')],
            },
        ),
    ]
