# Generated by Django 5.2.7 on 2025-10-30 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_days',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9\\-]{13,15}$', 'Enter a valid CNIC number.')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('master', 'Master Room'), ('meeting', 'Meeting Room'), ('deluxe', 'Deluxe Room'), ('executive', 'Executive Room'), ('suite', 'Luxury Suite')], max_length=50),
        ),
    ]
